// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9b7j0TSHtxmHItTMdRNDX16otLuoNDNE',
    appId: '1:772500291062:web:687aaf6a73e571118f9bd7',
    messagingSenderId: '772500291062',
    projectId: 'watchhub-94505',
    authDomain: 'watchhub-94505.firebaseapp.com',
    databaseURL: 'https://watchhub-94505-default-rtdb.firebaseio.com',
    storageBucket: 'watchhub-94505.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVFF4Mp1G_pzr-WYXelqysHo4NAlKntgI',
    appId: '1:772500291062:android:ce4d3d6c778640818f9bd7',
    messagingSenderId: '772500291062',
    projectId: 'watchhub-94505',
    databaseURL: 'https://watchhub-94505-default-rtdb.firebaseio.com',
    storageBucket: 'watchhub-94505.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgy1d-eJn3PPKHga6axktTmLIyzn7tivM',
    appId: '1:772500291062:ios:8c6820f4bf35b9bf8f9bd7',
    messagingSenderId: '772500291062',
    projectId: 'watchhub-94505',
    databaseURL: 'https://watchhub-94505-default-rtdb.firebaseio.com',
    storageBucket: 'watchhub-94505.firebasestorage.app',
    iosBundleId: 'com.example.flutterofflie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgy1d-eJn3PPKHga6axktTmLIyzn7tivM',
    appId: '1:772500291062:ios:8c6820f4bf35b9bf8f9bd7',
    messagingSenderId: '772500291062',
    projectId: 'watchhub-94505',
    databaseURL: 'https://watchhub-94505-default-rtdb.firebaseio.com',
    storageBucket: 'watchhub-94505.firebasestorage.app',
    iosBundleId: 'com.example.flutterofflie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9b7j0TSHtxmHItTMdRNDX16otLuoNDNE',
    appId: '1:772500291062:web:bebd470e62ede63d8f9bd7',
    messagingSenderId: '772500291062',
    projectId: 'watchhub-94505',
    authDomain: 'watchhub-94505.firebaseapp.com',
    databaseURL: 'https://watchhub-94505-default-rtdb.firebaseio.com',
    storageBucket: 'watchhub-94505.firebasestorage.app',
  );

}